doctrine:
    dbal:
        default_connection: core
        connections:
            core:
                url: '%env(resolve:DATABASE_CORE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

    orm:
        default_entity_manager: core
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        entity_managers:
            core:
                connection: core
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Core:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Core
                    Module:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Module'
                        prefix: 'App\Module'
                        alias: Module

when@test:
    doctrine:
        dbal:
            connections:
                core:
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            entity_managers:
                core:
                    query_cache_driver:
                        type: pool
                        pool: doctrine.system_cache_pool
                    result_cache_driver:
                        type: pool
                        pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
